spec:
  inputs:
    semver:
      description: The semantic version component to bump. Skip version update by choosing 'none' input
      options: ['major', 'minor', 'patch', 'none']
      default: 'none'
---

.default-workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"

.cache: &cache
  key:
    prefix: bundle
    files:
      - Gemfile.lock
  paths:
    - $BUNDLE_PATH
  policy: pull

default:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images/ci/debian-bookworm-slim-ruby-3.4.3:rubygems-3.6-git-2.49
  cache: *cache
  before_script:
    - bundle install

variables:
  BUNDLE_PATH: vendor/bundle
  BUNDLE_SILENCE_ROOT_WARNING: "true"
  GIT_STRATEGY: clone

workflow:
  rules:
    - !reference [.default-workflow, rules]
    - if: $CI_COMMIT_TAG

stages:
  - test
  - release

cache-gems:
  stage: .pre
  extends: .default-workflow
  variables:
    BUNDLE_FROZEN: "true" # ensure lockfile is in a proper state
  script:
    - echo "Cached ruby gems"
  cache:
    <<: *cache
    policy: pull-push

rubocop:
  extends: .default-workflow
  script:
    - bundle exec rubocop --color

rspec:
  extends: .default-workflow
  script:
    - bundle exec rspec --force-color spec
  coverage: '/Line Coverage: (\d+\.\d+%) \(.*\)$/'

bump-version:
  stage: release
  script:
    - bundle exec rake bump_version[$[[ inputs.semver ]]]
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.semver ]]" != "none"

# This job requires GEM_HOST_API_KEY variable to be set
release-gem:
  stage: release
  script:
    - bundle exec rake setup_git
    - bundle exec rake release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /Update version to v\d+\.\d+\.\d+/

# This job requires VERSION_UPDATE_TOKEN variable to be set
changelog:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:v0.23.0
  variables:
    CHANGELOG_FILE: CHANGELOG.md
    GITLAB_TOKEN: $VERSION_UPDATE_TOKEN
  before_script: []
  script:
    - glab changelog generate --version $CI_COMMIT_TAG > $CHANGELOG_FILE
  release:
    tag_name: $CI_COMMIT_TAG
    description: $CHANGELOG_FILE
  rules:
    - if: $CI_COMMIT_TAG
