inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

require:
  - rubocop-rspec

inherit_from:
  <% unless ENV['REVEAL_RUBOCOP_TODO'] == '1' %>
  - .rubocop_todo.yml
  <% end %>

inherit_mode:
  merge:
    - Include
    - Exclude
    - AllowedPatterns

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: disable

Rails:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
